services:
  postgres:
    image: postgres:17.6
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.4
    container_name: redis_cache
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - backend



volumes:
  postgres_data:
  redis_data:

networks:
  backend:
